CREATE TABLE followers (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , user_id INTEGER NOT NULL
  , follow_id INTEGER NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT 0
  , updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
) ENGINE = InnoDB
DEFAULT CHARACTER SET 'utf8';
